version: "3"
services:
  #
  # vcr-web
  #
  vcr-web:
    image: vcr-web
    environment:
      - DEBUG=${DEBUG}
      - API_URL=${API_URL}
      - APPLICATION_URL=${APPLICATION_URL}
      - IpFilterRules=${IpFilterRules}
      - RealIpFrom=${RealIpFrom}
      - HTTP_BASIC_USERNAME=${HTTP_BASIC_USERNAME}
      - HTTP_BASIC_PASSWORD=${HTTP_BASIC_PASSWORD}
      - WEB_BASE_HREF=${WEB_BASE_HREF}
      - WEB_DEPLOY_URL=${WEB_DEPLOY_URL}
    networks:
      - vcr
    ports:
      - "${WEB_HTTP_PORT}:8080"

networks:
  vcr:
    external:
      name: vcr_vcr